version: "3"
services:
  api:
    build: api
    container_name: api
    ports:
      - "8080:8080"
  auth:
    build: auth
    container_name: auth
    depends_on:
      - mongodb
      - api
    environment:
    - MONGODB_HOSTNAME=mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
