version: "3"
services:
  api:
    build: api
    container_name: api
    ports:
      - "8080:8080"
  chats:
    build: chats
    container_name: chats
    ports:
      - "8084:8080"
  auth:
    build:
      context: ./
      dockerfile: auth/Dockerfile
    container_name: auth
    depends_on:
      - mongodb-auth
      - api
    environment:
      - MONGODB_HOSTNAME=mongodb-auth
    ports:
      - "8082:8080"
  users:
    build:
      context: ./
      dockerfile: users/Dockerfile
    container_name: users
    depends_on:
      - mongodb-users
      - api
      - auth
    environment:
      - MONGODB_HOSTNAME=mongodb-auth
    ports:
      - "8081:8080"
  client:
    build: client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - api
      - auth
  mongodb-auth:
    image: mongo:latest
    container_name: mongodb-auth
  mongodb-users:
    image: mongo:latest
    container_name: mongodb-users

  mysql-chats:
    image: mysql
    container_name: mysql-chats
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=mudsigmoids
      - MYSQL_PASSWORD=mudsigmoids
      - MYSQL_DATABASE=dIRC
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"