import { useAuth } from '@/hooks/useAuth';
import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import { useState } from 'react';

const Home = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const { register, login, logout } = useAuth();

  const handleChanges: React.ChangeEventHandler<HTMLInputElement> = (e) => {
    const { name, value } = e.target;

    if (name === 'username') {
      setUsername(value);
    } else if (name === 'password') {
      setPassword(value);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form>
          <input
            name="username"
            type="text"
            placeholder="username"
            value={username}
            onChange={handleChanges}
          />
          <input
            name="password"
            type="password"
            placeholder="password"
            value={password}
            onChange={handleChanges}
          />
        </form>

        <button onClick={() => register(username, password)}>Register</button>
        <button onClick={() => login(username, password)}>Login</button>
        <button onClick={() => logout()}>Logout</button>
      </main>
    </>
  );
};

export default Home;
